let songs = [
	{
		num: 1,
		name: 'Cool',
		artist: 'Dua Lipa',
		cover: 'assets/images/cover 1.png',
		album: 'Future Nostalgia',
		length: '3:30',
	},
	{
		num: 2,
		name: 'Love Yourself',
		artist: 'Justin Beiber',
		cover: 'assets/images/cover 2.png',
		album: 'Holy',
		length: '2:40',
	},
	{
		num: 3,
		name: 'Jerusalema',
		artist: 'Master KG',
		cover: 'assets/images/cover 3.png',
		album: 'Grand Day',
		length: '2:00',
	},
	{
		num: 4,
		name: 'Picture Perfect',
		artist: 'DJ Khaled',
		cover: 'assets/images/cover 4.png',
		album: 'God Did',
		length: '2:47',
	},
	{
		num: 5,
		name: 'Mood',
		artist: 'Wizkid',
		cover: 'assets/images/cover 5.png',
		album: 'African Giant',
		length: '3:02',
	},
	{
		num: 6,
		name: 'Lolpop',
		artist: 'Lil Wayne',
		cover: 'assets/images/cover 6.png',
		album: 'Carter I',
		length: '3:19',
	},
	{
		num: 7,
		name: 'Hurricane',
		artist: 'artist 7',
		cover: 'assets/images/cover 7.png',
		album: 'Donda',
		length: '1:59',
	},
	{
		num: 8,
		name: 'Elevate',
		artist: 'Drake',
		cover: 'assets/images/cover 8.png',
		album: 'Certified Lover Boy',
		length: '3:47',
	},
	{
		num: 9,
		name: 'Hurricane',
		artist: 'J Cole',
		cover: 'assets/images/cover 9.png',
		album: 'Hollywood',
		length: '1:59',
	},
	{
		num: 10,
		name: 'Particular',
		artist: 'Nasty C',
		cover: 'assets/images/cover 10.png',
		album: 'C Remix',
		length: '1:59',
	},
	{
		num: 11,
		name: 'Hurricane',
		artist: 'Jay Z',
		cover: 'assets/images/cover 11.png',
		album: 'Hovah',
		length: '1:59',
	},
	{
		num: 12,
		name: 'Hurricane',
		artist: 'Beyonce',
		cover: 'assets/images/cover 12.png',
		album: 'Drunken Love',
		length: '1:59',
	},
	{
		num: 13,
		name: 'Hurricane',
		artist: 'Rihanna',
		cover: 'assets/images/cover 13.png',
		album: 'Umbrella',
		length: '1:59',
	},
];

export default songs;
